# Generated by Django 4.2.2 on 2023-07-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('assistant_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicHistory',
            fields=[
                ('clinic_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('PA', 'Personal administrativo'), ('PS', 'Personal de salud')], max_length=2)),
                ('area', models.CharField(verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('range', models.CharField(choices=[('AE', 'Auxiliar de enfermería'), ('ER', 'Enfermería registrada'), ('EE', 'Enfermería especializada'), ('EJ', 'Enfermera jefa'), ('ED', 'Enfermera directora')], max_length=2)),
                ('area', models.CharField(choices=[('EQ', 'Enfermería médico quirúrgica'), ('EP', 'Enfermería pediátrica'), ('EO', 'Enfermería obstétrica y ginecológica'), ('EI', 'Enfermería de cuidados intensivos'), ('ES', 'Enfermería de salud mental y psiquiátrica'), ('EC', 'Enfermería comunitaria')], max_length=2)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='authApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('assistant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='authApp.assistant')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='authApp.doctor')),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='authApp.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('document', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cellphone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('discharge_data', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vital_signs_id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetry', models.DecimalField(decimal_places=2, max_digits=3)),
                ('respiratory_rate', models.PositiveIntegerField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2)),
                ('systolic_blood_pressure', models.DecimalField(decimal_places=1, max_digits=3)),
                ('diastolic_blood_pressure', models.DecimalField(decimal_places=1, max_digits=2)),
                ('blood_glucose', models.DecimalField(decimal_places=2, max_digits=3)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('clinic_history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='authApp.clinichistory')),
                ('doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='authApp.doctor')),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='authApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('relative_id', models.AutoField(primary_key=True, serialize=False)),
                ('assistant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='authApp.assistant')),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='authApp.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relative_user', to='authApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to='authApp.user'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user', to='authApp.user'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='authApp.employee'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to='authApp.user'),
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('diagnostic_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('observations', models.CharField(max_length=4000)),
                ('treatment_effectiveness', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=1)),
                ('clinic_history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='authApp.clinichistory')),
                ('doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='authApp.doctor')),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='authApp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='clinichistory',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_history', to='authApp.patient'),
        ),
        migrations.CreateModel(
            name='CareTips',
            fields=[
                ('care_tips_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.CharField(max_length=4000)),
                ('diagnostic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tips', to='authApp.diagnostic')),
                ('doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_tips', to='authApp.doctor')),
                ('relative_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_tips', to='authApp.relative')),
            ],
        ),
        migrations.AddField(
            model_name='assistant',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='authApp.employee'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='authApp.user'),
        ),
    ]
