# Generated by Django 4.2.2 on 2023-07-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('PA', 'Personal administrativo'), ('PS', 'Personal de salud')], max_length=70),
        ),
    ]
