# Generated by Django 4.2.2 on 2023-07-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('1', 'Anestesiología'), ('2', 'Cardiología'), ('3', 'Dermatología'), ('4', 'Endocrinología'), ('5', 'Gastroenterología'), ('6', 'Geriatría'), ('7', 'Ginecología y Obstetricia'), ('8', 'Hematología'), ('9', 'Infectología'), ('10', 'Medicina de Emergencia'), ('11', 'Medicina Familiar y Comunitaria'), ('12', 'Medicina Interna'), ('13', 'Nefrología'), ('15', 'Neumología'), ('16', 'Neurología'), ('17', 'Oncología'), ('18', 'Oftalmología'), ('19', 'Ortopedia y Traumatología'), ('20', 'Otorrinolaringología'), ('21', 'Pediatría'), ('22', 'Psiquiatría'), ('23', 'Radiología'), ('24', 'Reumatología'), ('25', 'Urología')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('PA', 'Personal administrativo'), ('PS', 'Personal de salud')], max_length=2),
        ),
    ]
