# Generated by Django 4.2.2 on 2023-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_alter_doctor_speciality_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('ANE', 'Anestesiología'), ('CAR', 'Cardiología'), ('DER', 'Dermatología'), ('END', 'Endocrinología'), ('GAS', 'Gastroenterología'), ('GER', 'Geriatría'), ('GIN', 'Ginecología y Obstetricia'), ('HEM', 'Hematología'), ('INF', 'Infectología'), ('EME', 'Medicina de Emergencia'), ('FAM', 'Medicina Familiar y Comunitaria'), ('INT', 'Medicina Interna'), ('NEF', 'Nefrología'), ('NEU', 'Neumología'), ('NER', 'Neurología'), ('ONC', 'Oncología'), ('OFT', 'Oftalmología'), ('ORT', 'Ortopedia y Traumatología'), ('OTO', 'Otorrinolaringología'), ('PED', 'Pediatría'), ('PSQ', 'Psiquiatría'), ('RAD', 'Radiología'), ('REU', 'Reumatología'), ('URO', 'Urología')], max_length=3),
        ),
    ]
