# Generated by Django 4.2.2 on 2023-07-16 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='next_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
