# Generated by Django 4.2.2 on 2023-07-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_diagnostic_next_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('main_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('main_post_img', models.ImageField(upload_to='main_post')),
                ('tittle', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
